app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse
from prometheus_client import generate_latest

def metrics_view(request):
    data = generate_latest()
    return HttpResponse(data, content_type='text/plain')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('books.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('fav/', include('favs.urls', namespace='fav')),
    path('metrics', metrics_view, name='prometheus-metrics'),
    path('__debug__/', include('debug_toolbar.urls')),

]

books/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from books import views
from django_prometheus.exports import ExportToDjangoView


app_name = 'catalog'

urlpatterns = [
    path('', views.catalog, name='index'), 
    path('fantastika/', views.catalog, name='fantastika'),
    path('book/<slug:book_slug>/', views.book, name='book'), 
    path('<slug:genre_slug>/', views.catalog, name='index'),
    path('book/create/', views.create_book, name='create_book'),
    path('book/<slug:book_slug>/update/', views.update_book, name='update_book'),
    path('book/<slug:book_slug>/delete/', views.delete_book, name='delete_book'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-fav/', views.users_fav, name='users_fav'),
    path('logout/', views.logout, name='logout'),
    path('add_book/', views.add_book, name='add_book'),
    path('my_books/', views.my_books, name='my_books'),
    path('delete_book/<uuid:book_id>/', views.delete_book, name='delete_book'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    contact = models.CharField(max_length=150, null=True, verbose_name='Контакты')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
            model = User
            fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "contact",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    contact = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
            "contact")


    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    contact = forms.CharField()

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages


from books.models import Books
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from books.forms import BookForm

def login(request):

    if request.method == "POST":

        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")
                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = { 
        'title': 'Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)



def registration(request):
    if request.method == 'POST':
            form = UserRegistrationForm(data=request.POST)
            if form.is_valid():
                form.save()
                user = form.instance
                auth.login(request, user)
                messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успешно обновлен")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Личный Кабинет',
        'form': form
    }
    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

def users_fav(request):
    return render(request, 'users/users_fav.html')

@login_required
def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            return redirect('users:profile')
    else:
        form = BookForm(user=request.user) 
    return render(request, 'users/add_book.html', {'form': form}) 

@login_required
def delete_book(request, book_id):
    book = Books.objects.get(pk=book_id)
    if book.owner == request.user:  # пользователь влаеет книгой
        book.delete()
        return redirect('users:profile')  
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def my_books(request):
    books = Books.objects.filter(owner=request.user)  # получаем книги текущего пользователя
    return render(request, 'users/my_books.html', {'books': books})

users/templates/users/add_book.html
{% extends "base.html" %}
{% load static %}
{% block modal_fav %}
{% include "includes/fav_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Добавление книги</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Добавить книгу</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_fav %}
{% include "includes/fav_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" id="id_username"
                        placeholder="Введите ваше имя пользователя"
                        required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" name="password" id="id_password"
                        placeholder="Введите ваш пароль" required>
                    </div>

                    {% comment %} <div class="mb-3">
                        <label for="username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                    </div>{% endcomment %}
                    <button type="submit" class="btn btn-dark btn-block">Войти</button> 
                </form>
                <div class="mt-3">
                    <a href="{% url "users:registration" %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/my_books.html
{% extends 'base.html' %}
{% load static %}
{% load favs_tags %}
{% block content %}
  <div class="container">
    <h2>Мои книги</h2>
    {% if books %}
      <div class="row">
        {% for book in books %}
          <div class="col-md-4 mb-4">
            <div class="card">
              <img src="{{ book.image.url }}" class="card-img-top" alt="{{ book.name }}">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url "catalog:book" book.slug %}">{{ book.name }}</a></h5>
                <p class="card-text">Автор: {{ book.author }}</p>
                <div class="d-flex justify-content-end">
                  <a href="{% url 'users:delete_book' book.id %}" class="btn btn-danger">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p class="text-center">Вы еще не добавили ни одной книги.</p>
    {% endif %}
  </div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load favs_tags %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">

            <div class="col-md-6">
                <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/images/baseavatar.jpg" %}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image" name="image" accept="image/*">
                                {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Введите ваше имя" value="{{ form.first_name.value }}" required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username" name="username" placeholder="Введите ваше имя пользователя" value="{{ form.username.value }}" required>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email" name="email" placeholder="Введите ваш email *youremail@example.com" value="{{ form.email.value }}" required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_contact" class="form-label">Контактная информация</label>
                                <input type="text" class="form-control" id="id_contact" name="contact" placeholder="Введите ваши контакты" value="{{ form.contact.value }}">
                                {% if form.contact.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.contact.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="bg-white p-4 mb-3 mx-5 rounded custom-shadow">
                    <div class="category-buttons d-flex justify-content-between mb-4">
                        <a href="{% url "users:add_book" %}" class="btn btn-secondary">Добавить книгу</a>
                        <a href="{% url 'users:my_books' %}" class="btn btn-secondary">Мои книги</a>
                    </div>
                    <br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}
{% block modal_fav %}
{% include "includes/fav_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action = "{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value = "{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
                                name = "first_name"
                                placeholder="Введите ваше имя" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value = "{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
                                name = "last_name"
                                placeholder="Введите вашу фамилию" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                value = "{% if form.username.value %}{{form.username.value}}{% endif %}"
                                name = "username"
                                placeholder="Введите ваше имя пользователя" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value = "{% if form.email.value %}{{form.email.value}}{% endif %}"
                                name = "email"
                                placeholder="Введите ваш email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_contact" class="form-label">Для связи*</label>
                            <input type="contact" class="form-control" id="id_contact"
                                value = "{% if form.contact.value %}{{form.contact.value}}{% endif %}"
                                name = "contact"
                                placeholder="Введите номер для связи с Вами" required>
                                {% if form.contact.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.contact.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value = "{% if form.password1.value %}{{form.password1.value}}{% endif %}"
                                name = "password1"
                                placeholder="Введите пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value = "{% if form.password2.value %}{{form.password2.value}}{% endif %}"
                                name = "password2"
                                placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_fav.html
{% extends "base.html" %}
{% load static %}
{% load favs_tags %}

{% block content %}
{% user_favs request as favs %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Избранное</h3>
                <div class="container" id="fav-items-container"
                    {% include "favs/includes/included_fav.html" %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}